ALTER TABLE users ADD COLUMN wechat_openid VARCHAR(128) NULL;
ALTER TABLE users ADD COLUMN wechat_id VARCHAR(64) NULL;
ALTER TABLE users ADD COLUMN qq VARCHAR(32) NULL;
ALTER TABLE users MODIFY COLUMN email VARCHAR(128) NULL;
ALTER TABLE users MODIFY COLUMN password_hash VARCHAR(255) NULL;
ALTER TABLE users ADD CONSTRAINT uk_users_wechat_openid UNIQUE (wechat_openid);
